#!/usr/bin/env python3
"""Regenerate the local OpenCode Web theme registry.

This script mirrors the official OpenCode Web built-in theme registry into
`lib/presentation/theme/opencode_web_theme_registry.dart`.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable
from urllib.request import urlopen


DEFAULT_THEMES_URL = (
    "https://raw.githubusercontent.com/anomalyco/opencode/dev/"
    "packages/ui/src/theme/default-themes.ts"
)
THEME_JSON_URL_TEMPLATE = (
    "https://raw.githubusercontent.com/anomalyco/opencode/dev/"
    "packages/ui/src/theme/themes/{theme_id}.json"
)
REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "lib/presentation/theme/opencode_web_theme_registry.dart"


def fetch_text(url: str) -> str:
    with urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def fetch_json(url: str) -> dict[str, object]:
    return json.loads(fetch_text(url))


def parse_theme_ids(default_themes_source: str) -> list[str]:
    match = re.search(
        r"export const DEFAULT_THEMES:.*?= \{(?P<body>.*?)\n\}",
        default_themes_source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError("Could not locate DEFAULT_THEMES object in source")
    body = match.group("body")
    ids: list[str] = []
    for raw_line in body.splitlines():
        line = raw_line.strip().rstrip(",")
        if not line or line.startswith("//"):
            continue
        key, _, _ = line.partition(":")
        key = key.strip()
        if key.startswith("[") and key.endswith("]"):
            key = key[1:-1].strip()
        if key.startswith(('"', "'")) and key.endswith(('"', "'")):
            key = key[1:-1]
        ids.append(key)
    if not ids:
        raise RuntimeError("No theme ids parsed from DEFAULT_THEMES object")
    return ids


def dart_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def dart_color(value: str) -> str:
    return f"Color(0xFF{value.removeprefix('#').upper()})"


def emit_lines() -> Iterable[str]:
    default_themes_source = fetch_text(DEFAULT_THEMES_URL)
    theme_ids = parse_theme_ids(default_themes_source)

    yield "// GENERATED CODE - DO NOT MODIFY BY HAND."
    yield "//"
    yield "// Generated by: tool/theme/generate_opencode_web_themes.py"
    yield "// Source of truth: official OpenCode Web theme registry"
    yield f"// - {DEFAULT_THEMES_URL}"
    yield "// - packages/ui/src/theme/themes/<theme-id>.json"
    yield ""
    yield "import 'package:flutter/material.dart';"
    yield ""
    yield "@immutable"
    yield "class OpenCodeThemePaletteData {"
    yield (
        "  const OpenCodeThemePaletteData({required this.neutral, required this.ink, "
        "required this.primary, required this.success, required this.warning, "
        "required this.error, required this.info, this.accent, this.interactive, "
        "this.diffAdd, this.diffDelete});"
    )
    yield "  final Color neutral;"
    yield "  final Color ink;"
    yield "  final Color primary;"
    yield "  final Color success;"
    yield "  final Color warning;"
    yield "  final Color error;"
    yield "  final Color info;"
    yield "  final Color? accent;"
    yield "  final Color? interactive;"
    yield "  final Color? diffAdd;"
    yield "  final Color? diffDelete;"
    yield "}"
    yield ""
    yield "@immutable"
    yield "class OpenCodeThemeVariantData {"
    yield (
        "  const OpenCodeThemeVariantData({required this.palette, "
        "this.overrides = const <String, Color>{}});"
    )
    yield "  final OpenCodeThemePaletteData palette;"
    yield "  final Map<String, Color> overrides;"
    yield "}"
    yield ""
    yield "@immutable"
    yield "class OpenCodeThemeDefinitionData {"
    yield (
        "  const OpenCodeThemeDefinitionData({required this.id, required this.name, "
        "required this.light, required this.dark});"
    )
    yield "  final String id;"
    yield "  final String name;"
    yield "  final OpenCodeThemeVariantData light;"
    yield "  final OpenCodeThemeVariantData dark;"
    yield "}"
    yield ""
    yield "const List<OpenCodeThemeDefinitionData> kOpenCodeWebThemes = "
    yield "    <OpenCodeThemeDefinitionData>["

    for theme_id in theme_ids:
        data = fetch_json(THEME_JSON_URL_TEMPLATE.format(theme_id=theme_id))
        yield "  OpenCodeThemeDefinitionData("
        yield f"    id: {dart_string(str(data['id']))},"
        yield f"    name: {dart_string(str(data['name']))},"
        for variant_key in ("light", "dark"):
            variant = data[variant_key]
            if not isinstance(variant, dict):
                raise RuntimeError(
                    f"Theme {theme_id} has invalid {variant_key} variant"
                )
            palette = variant.get("palette")
            if not isinstance(palette, dict):
                raise RuntimeError(
                    f"Theme {theme_id} missing palette for {variant_key}"
                )
            yield f"    {variant_key}: OpenCodeThemeVariantData("
            yield "      palette: OpenCodeThemePaletteData("
            for key in (
                "neutral",
                "ink",
                "primary",
                "success",
                "warning",
                "error",
                "info",
            ):
                yield f"        {key}: {dart_color(str(palette[key]))},"
            for optional_key in ("accent", "interactive", "diffAdd", "diffDelete"):
                if optional_key in palette:
                    yield f"        {optional_key}: {dart_color(str(palette[optional_key]))},"
            yield "      ),"
            overrides = variant.get("overrides", {})
            if not isinstance(overrides, dict):
                raise RuntimeError(f"Theme {theme_id} overrides must be an object")
            if overrides:
                yield "      overrides: <String, Color>{"
                for key, value in overrides.items():
                    yield f"        {dart_string(str(key))}: {dart_color(str(value))},"
                yield "      },"
            yield "    ),"
        yield "  ),"

    yield "];"
    yield ""
    yield "OpenCodeThemeDefinitionData? openCodeWebThemeDefinitionForId(String id) {"
    yield "  for (final theme in kOpenCodeWebThemes) {"
    yield "    if (theme.id == id) {"
    yield "      return theme;"
    yield "    }"
    yield "  }"
    yield "  return null;"
    yield "}"


def generate_registry() -> str:
    return "\n".join(emit_lines()) + "\n"


def format_generated_content(content: str) -> str:
    try:
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir) / OUTPUT_PATH.name
            temp_path.write_text(content)
            subprocess.run(
                ["dart", "format", str(temp_path)],
                check=True,
                cwd=REPO_ROOT,
                capture_output=True,
            )
            return temp_path.read_text()
    except FileNotFoundError:
        return content


def run_dart_format(path: Path) -> None:
    try:
        subprocess.run(["dart", "format", str(path)], check=True, cwd=REPO_ROOT)
    except FileNotFoundError:
        print(
            "warning: dart not found; generated file left unformatted", file=sys.stderr
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the generated output differs from the checked-in file.",
    )
    args = parser.parse_args()

    generated = format_generated_content(generate_registry())
    current = OUTPUT_PATH.read_text() if OUTPUT_PATH.exists() else None

    if args.check:
        if current != generated:
            print(
                f"{OUTPUT_PATH} is out of date. Run {Path(__file__).relative_to(REPO_ROOT)}."
            )
            return 1
        print(f"{OUTPUT_PATH} is up to date.")
        return 0

    OUTPUT_PATH.write_text(generated)
    run_dart_format(OUTPUT_PATH)
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
